package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.neusoft.tdframework.authorization.*;
import com.neusoft.tdframework.common.GlobalParameters;
import com.neusoft.tdframework.common.util.PassWord;
import com.neusoft.unieap.config.EAPConfigHelper;
import com.neusoft.unieap.ria.config.RIAConfig;
import com.neusoft.unieap.service.org.Person;

public final class portalpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/unieap/ria3.3/pages/config.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String webpath = request.getContextPath();

AuthorizeVO authorizeVO = (AuthorizeVO)session.getAttribute(GlobalParameters.SESSION_INFO);
String employeeId = authorizeVO.getEmployeeId();

StringBuffer paramStr = new StringBuffer();
String userName = authorizeVO.getWorkNo();
String userNameDes = authorizeVO.getEmployeeName();
String passWord = PassWord.decode(authorizeVO.getWorkPwd());
paramStr.append("j_username=").append(userName).append("&j_password=").append(passWord);

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\r\n");
      out.write("\t\t\"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("<html style=\"overflow-y:auto;overflow-x:hidden;\">\r\n");
      out.write("<head>\r\n");
      out.write("<META HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\"> \r\n");
      out.write("<META HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache\"> \r\n");
      out.write("<META HTTP-EQUIV=\"Expires\" CONTENT=\"0\">\r\n");
      out.write("<title>欢迎登录 中国电信 BSS系统</title>\r\n");
      out.write("<contextPath value=\"");
      out.print(webpath);
      out.write("\"/>\r\n");
      out.write("\r\n");
out.println("<script type='text/javascript'>function getcontext(){var APP_PATH = '"+webpath+"'; return APP_PATH;}</script>");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\t\t@import \"");
      out.print(webpath);
      out.write("/unieap/ria3.3/dojox/layout/resources/GridContainer.css\";\r\n");
      out.write("\t\t.dj_ie6 .dropIndicator, .dj_ie6 .dojoxPortlet{\r\n");
      out.write("\t\t\tmargin: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.gridContainerZone > *{\r\n");
      out.write("\t\t\tmargin: 5px !important;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
    String appPath = EAPConfigHelper.getApplicationContextPath(request);
    String cmpPath = request.getRequestURI(); //è·åé¡µé¢è·¯å¾å°å
    String themePath = path + "/unieap/ria3.3/unieap/themes/blue/css";
    boolean dialogRelogin= RIAConfig.DIALOGRELOGIN;//è®¾ç½®æ¯å¦ä½¿ç¨Dialogè¿è¡éæ°ç»å½
    boolean PUBLICATION = RIAConfig.PUBLICATION; //è®¾ç½®æ¯å¦
	boolean isEncrypt = RIAConfig.ENCRYPT;//æ¯å¦ä½¿ç¨å å¯
	Person person = (Person) session.getAttribute("userinfo");
	
	
	java.util.Properties envProp = (java.util.Properties)request.getSession().getServletContext().getAttribute("ENVCONF");
	//System.out.println("???????????????????????????????????    " + envProp.getProperty("td.jscompress.flag"));
	boolean isCompressJs = false;
	if ("1".equals(envProp.getProperty("td.usejscompress.flag"))) {
		isCompressJs = true;
	}

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tmargin : 0px;\r\n");
      out.write("\t\tvisibility : hidden;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//var beginTime = new Date();\r\n");
      out.write("\t//åå§åç³»ç»åæ°\r\n");
      out.write("\tunieap = {};\r\n");
      out.write("\tunieap.WEB_APP_NAME = \"");
      out.print(path);
      out.write("\";\r\n");
      out.write("\tunieap.appPath = \"");
      out.print(appPath);
      out.write("\";\r\n");
      out.write("\tunieap.cmpPath = \"");
      out.print(cmpPath);
      out.write("\"; //unieap.cmpPathç¨äºgridèªå®ä¹ä¸­\r\n");
      out.write("\tunieap.dialogRelogin=\"");
      out.print(dialogRelogin);
      out.write("\";\r\n");
      out.write("\tunieap.isEncrypt = \"");
      out.print(isEncrypt);
      out.write("\";\r\n");
      out.write("\tunieap.loginAccount = '");
      out.print((person!=null?person.getAccount():""));
      out.write("';\r\n");
      out.write("\tunieap.locale = \"zh_CN\";\r\n");
      out.write("</script>\r\n");
      out.write(" <!--  \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
//=path
      out.write("/unieap/ria3.3/unieap/themes/base/css/unieap.css\" charset=\"utf-8\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
//=themePath
      out.write('/');
//=PUBLICATION?"unieap-all.css":"unieap.css"
      out.write("\" ></link>\r\n");
      out.write("-->\r\n");
if(!isCompressJs) {//if(!PUBLICATION){ 
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/themes/base/css/unieap.css\" charset=\"utf-8\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(themePath);
      out.write('/');
      out.print(PUBLICATION?"unieap-all.css":"unieap.css");
      out.write("\" ></link>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/dojo/dojo.js\" djConfig=\" parseOnLoad: true,locale:'zh'\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/patch/dojo-patch.js\"  charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/dijit/dijit.js\"  charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/nls/application_zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/global.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/cache.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/rpc.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/Form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/FieldSet.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/TextBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/InlineEditBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/Textarea.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/NumberTextBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/TextBoxWithIcon.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/ComboBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/DateTextBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/ComboBoxTree.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/Button.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/DropDownButton.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/CheckBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/RadioButton.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/CheckBoxGroup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/RadioButtonGroup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/FileInput.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/tree/Tree.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/Container.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/TitlePane.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/TabContainer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/AdaptiveContainer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/BorderContainer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/BorderPane.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/HBoxContainer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/layout/VBoxContainer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/grid/Grid.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/core/lib.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/core/cell.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/Manager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/core/rowbar.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/LayoutManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/core/builder.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/core/view.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/core/scroller.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/ViewManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/RowManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/BindingManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/MenuManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/SelectionManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/RowEditManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/PagingManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/ExportManager.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/menu/lockcell.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/menu/showcell.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/manager/Individual.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/core/toolbar.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/xgrid/Grid.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/dialog/DialogUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/dialog/MessageBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/menu/Menu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/Tooltip.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/form/RichTextEditor.js\"></script>\r\n");
} else{
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
//=path
      out.write("/unieap/ria3.3/dojo/dojo.js\" djConfig=\"parseOnLoad: true,locale:'zh'\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
//=path
      out.write("/unieap/ria3.3/unieap/nls/application_zh_CN.js\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<!--å°global.jsæä»¶ç¬ç«åºæ¥,ç¨æ¥å¯ä»¥å¨æ­¤å¤å¼å¥èªå·±çglobal.jsæä»¶ -->\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
//=path
      out.write("/unieap/ria3.3/unieap/global.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
//=path
      out.write("/unieap/ria3.3/unieap/unieap-all.js\" ></script>\r\n");
      out.write(" -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(themePath);
      out.write("/unieap-combo.css\" ></link>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/themes/base/css/tooltip.css\" ></link>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/unieap/ria3.3/unieap/themes/blue/css/tooltip.css\" ></link>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/dojo/dojo.js\" djConfig=\"parseOnLoad: true,locale:'zh'\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/dijit/dijit.js\"  charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/ria3.3/pages/unieap-combo.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//var jsTime = new Date();\r\n");
      out.write("\tdojo.addOnLoad(function(){\r\n");
      out.write("\t\tdojo.style(document.body,\"visibility\",\"visible\");\r\n");
      out.write("\t\t//è®¾ç½®å®¹å¨çå¤§å°\r\n");
      out.write("\t\t//unieap.fireContainerResize();\t\r\n");
      out.write("\t\t//è§£å³å¨dojo.addOnLoadæ¹æ³éæ§ä»¶èç¦çé®é¢\r\n");
      out.write("\t\tunieap.blurWidget();\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\tunieap.session.dialogRelogin=");
      out.print(dialogRelogin);
      out.write(";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" id=\"themeStyles\" href=\"");
      out.print(webpath);
      out.write("/unieap/ria3.3/dijit/themes/claro/claro.css\">\r\n");
      out.write("<link href=\"");
      out.print(webpath);
      out.write("/common/dx20/css/crm6_portal.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(webpath);
      out.write("/home/portalpage.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t    dojo.require(\"dojox.json.query\");\r\n");
      out.write("\r\n");
      out.write("\t    dojo.require(\"dijit.Tooltip\");\r\n");
      out.write("\t\tdojo.require(\"dijit.TooltipDialog\");\r\n");
      out.write("\t\tdojo.require(\"dojox.widget.DialogSimple\");\r\n");
      out.write("\t\tdojo.require(\"dojox.widget.Dialog\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdojo.require(\"dijit.form.MultiSelect\");\r\n");
      out.write("\t\tdojo.provide(\"dojo.data.ObjectStore\");\r\n");
      out.write("\t\tdojo.require(\"dojo.store.DataStore\");\r\n");
      out.write("\t\tdojo.require(\"dojo.store.Memory\");\r\n");
      out.write("\t\tdojo.require(\"unieap.layout.TDPortalTitlePane\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar employeeid = \"");
      out.print(employeeId);
      out.write("\";\r\n");
      out.write("\t\tvar settingPortalTempStore = new dojo.store.Memory();\r\n");
      out.write("\t\tvar settingPortalTempHeight = new dojo.store.Memory();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//dojo.cookie(\"viewToMenuRela\" + employeeid,\"\");\r\n");
      out.write("\t\t//alert(\"11111111111   \"+employeeid+\"     \" + dojo.cookie(\"viewToMenuRela\" + employeeid));\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t    var authQueryStr = parent.parent.getJsParaAutoPara();   //\"");
//=paramStr.toString()
      out.write("\";\r\n");
      out.write("\t    \r\n");
      out.write("\t    var isToolDialogOpenned = false;\r\n");
      out.write("\t    \r\n");
      out.write("\t    var tempSettingSelectView;\r\n");
      out.write("\t    var tempSettingHeightSelectView;\r\n");
      out.write("\t\r\n");
      out.write("\t    var mod = new ModTreeClass();\r\n");
      out.write("\t\tdojo.subscribe(\"/dojox/mdnd/drop\", function(theNews){\r\n");
      out.write("\t\t\tmod.subscribeLayout();\r\n");
      out.write("\t\t });  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdojo.addOnLoad(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar isIe7 = false;\r\n");
      out.write("\t\t\tif(navigator.appName == \"Microsoft Internet Explorer\")\r\n");
      out.write("\t\t\t {\r\n");
      out.write("\t\t\t   if(navigator.appVersion.match(/7./i)=='7.')\r\n");
      out.write("\t\t\t   {\r\n");
      out.write("\t\t\t\t   document.body.style.overflowY=\"hidden\";\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\tmod.getViewInfo();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetTimeZone();\r\n");
      out.write("\t\t\tgetTitleInfo();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getTitleInfo() {\r\n");
      out.write("\t\t\tvar tInfo = null;\r\n");
      out.write("\t\t\t/**/\r\n");
      out.write("\t\t\tdojo.rawXhrPost({\r\n");
      out.write("\t\t\t\turl : getcontext() + \"/portalpage.do?actionMethod=getTitleInfo\",\r\n");
      out.write("\t\t\t\tsync : false,\r\n");
      out.write("\t\t\t\tload : function(text, args) {\r\n");
      out.write("\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t//alert(text);\r\n");
      out.write("\t\t\t\t\t\ttInfo = dojo.fromJson(text);\r\n");
      out.write("\t\t\t\t\t\t//alert(tInfo[\"lastLoginTime\"]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif (tInfo != null) {\r\n");
      out.write("\t\t\t\t\t\t\tdojo.byId(\"onlineNumner\").innerHTML = \"<font color='blue'><b>\" + tInfo[\"onlineNumner\"] + \"</b></font>\";\r\n");
      out.write("\t\t\t\t\t\t\tdojo.byId(\"lastLoginTime\").innerHTML = tInfo[\"lastLoginTime\"];\r\n");
      out.write("\t\t\t\t\t\t\t//dojo.byId(\"noReadWraning\").innerHTML = \"<font color='blue'><b>\" + tInfo[\"noReadWraning\"] + \"</b></font>\";\r\n");
      out.write("\t\t\t\t\t\t\t//dojo.byId(\"noComMission\").innerHTML = \"<font color='blue'><b>\" + tInfo[\"noComMission\"] + \"</b></font>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\t\talert(\"读取Portal信息失败。\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("            \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checklayout(sel) {\r\n");
      out.write("\t\t\tvar container =  dijit.byId(\"gridContainer\");\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tdojo.cookie(\"portalContainerColums-\"+dojo.byId(\"viewSel\").options[dojo.byId(\"viewSel\").selectedIndex].value,\r\n");
      out.write("\t\t\t    \t\tsel);\r\n");
      out.write("\r\n");
      out.write("\t\t\t    container.set(\"colWidths\", sel);\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t//\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkViewSel(sel) {\r\n");
      out.write("\t\t\tmod.clearPortalContainer();\r\n");
      out.write("\t\t\tmod.unsubscribeAllHandler();\r\n");
      out.write("\t\t\tmod.createPortalet(sel.options[sel.selectedIndex].value);\r\n");
      out.write("\t\t\tmod.createPortaletSubMenu();\r\n");
      out.write("\t\t\tgetTimeZone();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkColNumSel(sel) {\r\n");
      out.write("\t\t\tmod.clearPortalContainer();\r\n");
      out.write("\t\t\tmod.unsubscribeAllHandler();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar selectedColNum = sel.options[sel.selectedIndex].value;\r\n");
      out.write("\t\t\tif (selectedColNum == null || selectedColNum == \"\") {\r\n");
      out.write("\t\t\t\tselectedColNum = 3;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmod.containerColumn = selectedColNum;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar container =  dijit.byId(\"gridContainer\");\r\n");
      out.write("\t\t\tcontainer.setColumns(mod.containerColumn);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar cLay = mod.containerLayout;\r\n");
      out.write("\t\t\tvar layoutSel = dojo.byId(\"layoutSel\");\r\n");
      out.write("\t\t\tlayoutSel.options.length = 0;\r\n");
      out.write("\t\t\tfor (var i = 0; i < cLay[mod.containerColumn].length; i++) {\r\n");
      out.write("\t\t\t\tlayoutSel.add(new Option(cLay[mod.containerColumn][i],cLay[mod.containerColumn][i]));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t    container.set(\"colWidths\", layoutSel.options[0].value);\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t//\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar viewValue = dojo.byId(\"viewSel\");\r\n");
      out.write("\t\t\tmod.createPortalet(viewValue.options[viewValue.selectedIndex].value);\r\n");
      out.write("\t\t\tmod.createPortaletSubMenu();\r\n");
      out.write("\t\t\tdojo.cookie(\"portalColNumber\",\r\n");
      out.write("\t\t\t\t\tmod.containerColumn);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction refleshPortalPage() {\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\tvar viewValue = dojo.byId(\"viewSel\");\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\tvar viewId = viewValue.options[viewValue.selectedIndex].value;\r\n");
      out.write("\t            dojo.cookie(\"portalLayout_\" + employeeid + \"_\" + viewId,\"\");\r\n");
      out.write("\t            dojo.cookie(\"portalContainerColums-\"+viewId,\"\");\r\n");
      out.write("\t            dojo.cookie(\"viewToMenuRela\" + employeeid,\"\");\r\n");
      out.write("\t\t\t\tdojo.cookie(\"menuHeightSetting\" + employeeid,\"\");\r\n");
      out.write("\t\t\t\tmod.viewsMenuInfoJson = null;\r\n");
      out.write("\t\t\t\tsettingPortalTempStore = null;\r\n");
      out.write("\t\t\t\tsettingPortalTempHeight = null;\r\n");
      out.write("\t\t\t\tisToolDialogOpenned = false;\r\n");
      out.write("\t\t\t\tvar viewIds = \"\";\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < mod.viewInfoJson.length; i++) {\r\n");
      out.write("\t\t\t\t\tif (i == 0) {\r\n");
      out.write("\t\t\t\t\t\tviewIds = viewIds + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tviewIds = viewIds + \"~\" + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tmod.initSettingInfo(viewIds, \"\", true);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t            mod.clearPortalContainer();\r\n");
      out.write("\t            mod.unsubscribeAllHandler();\r\n");
      out.write("\t           \r\n");
      out.write("\t\t\t\tmod.createPortalet(viewId);\r\n");
      out.write("\t\t\t\tmod.createPortaletSubMenu();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tgetTimeZone();\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction confirmSetting() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tdojo.byId(\"alertDiv\").style.display = \"none\";\r\n");
      out.write("            dojo.byId(\"settingDiv\").style.display = \"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction onSettingDiaShow() {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\tvar viewIds = \"\";\r\n");
      out.write("\t\t\tfor (var i = 0; i < mod.viewInfoJson.length; i++) {\r\n");
      out.write("\t\t\t\tif (i == 0) {\r\n");
      out.write("\t\t\t\t\tviewIds = viewIds + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tviewIds = viewIds + \"~\" + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmod.initSettingInfo(viewIds, \"\", false);\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction leftToRight(dirct) {\r\n");
      out.write("\t\t\tif (dirct == 0) {\r\n");
      out.write("\t\t\t\tdijit.byId(\"selectViewsPoint\").addSelected(dijit.byId(\"selectViewsAll\")); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdijit.byId(\"selectViewsAll\").addSelected(dijit.byId(\"selectViewsPoint\")); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkviewSelectSet(sel) {\r\n");
      out.write("\t\t\tvar viewIds = \"\";\r\n");
      out.write("\t\t\tfor (var i = 0; i < mod.viewInfoJson.length; i++) {\r\n");
      out.write("\t\t\t\tif (i == 0) {\r\n");
      out.write("\t\t\t\t\tviewIds = viewIds + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tviewIds = viewIds + \"~\" + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar tempPoint = mod.getMulSelectOptions(tempSettingSelectView);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    if (settingPortalTempStore != null && settingPortalTempStore != \"\" && dojo.toJson(tempPoint) != dojo.toJson(settingPortalTempStore.get(tempSettingSelectView+\"tempselect\"))) {\r\n");
      out.write("\t\t    \t//alert(dojo.toJson(tempPoint) +\"-----------------\"+ dojo.toJson(settingPortalTempStore.get(tempSettingSelectView+\"tempselect\")));\r\n");
      out.write("\t\t    \tfor (var i = 0; i < sel.options.length; i++) {\r\n");
      out.write("\t\t\t\t\tif (sel.options[i].value == tempSettingSelectView) {\r\n");
      out.write("\t\t\t\t\t\tsel.options[i].selected=\"selected\";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    \tdojo.byId(\"alertDiv\").style.display = \"block\";\r\n");
      out.write("\t            dojo.byId(\"settingDiv\").style.display = \"none\";\r\n");
      out.write("\t            dojo.byId(\"alertDiv\").innerHTML = \"<br><br><br><br><br><br><br>您做的设置还没有应用，请在设置页面点击\\\"应用\\\"按钮或\\\"取消\\\"按钮。<br><br><br><br><div align=center><input type=button value='    确定    ' onclick='confirmSetting();'></input></div>\";\r\n");
      out.write("\t\t    \treturn false;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\tmod.initSettingInfo(viewIds,sel.options[sel.selectedIndex].value ,true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction checkviewSelectSetHeight(sel) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar viewSelect = sel.options[sel.selectedIndex].value;\r\n");
      out.write("\t\t\tvar vali = mod.generateInputMenu(viewSelect);\r\n");
      out.write("\t\t\tif (vali == false) {\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < sel.options.length; i++) {\r\n");
      out.write("\t\t\t\t\tif (sel.options[i].value == tempSettingHeightSelectView) {\r\n");
      out.write("\t\t\t\t\t\tsel.options[i].selected=\"selected\";\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction applySettingClick() {\r\n");
      out.write("\t\t\tvar sel = dojo.byId(\"viewSelectSet\");\r\n");
      out.write("\t\t\tvar viewSelect = sel.options[sel.selectedIndex].value;\r\n");
      out.write("\t\t\tsettingPortalTempStore.put(mod.getMulSelectOptions(viewSelect));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction applySettingHeightClick() {\r\n");
      out.write("\t\t\t//unieap.debug(settingPortalTempHeight);\r\n");
      out.write("\t\t\tvar sel = dojo.byId(\"viewSelectSetMenu\");\r\n");
      out.write("\t\t\tvar viewSelect = sel.options[sel.selectedIndex].value;\r\n");
      out.write("\t\t\tvar temHeights = settingPortalTempHeight.get(viewSelect+\"tempHeight\")[\"value\"];\r\n");
      out.write("\t\t\tfor (var i = 0; i < temHeights.length; i++) {\r\n");
      out.write("\t\t\t\tvar inputHeight = unieap.byId(temHeights[i][\"menu_Id\"]+\"HeightInput\").getValue();\r\n");
      out.write("\t\t\t\ttemHeights[i][\"f_Height\"] = inputHeight;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//unieap.debug(settingPortalTempHeight);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction cancelSettingClick() {\r\n");
      out.write("\t\t\tvar viewIds = \"\";\r\n");
      out.write("\t\t\tfor (var i = 0; i < mod.viewInfoJson.length; i++) {\r\n");
      out.write("\t\t\t\tif (i == 0) {\r\n");
      out.write("\t\t\t\t\tviewIds = viewIds + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tviewIds = viewIds + \"~\" + mod.viewInfoJson[i][\"view_Id\"];\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmod.initSettingInfo(viewIds,tempSettingSelectView ,true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction cancelSettingHeightClick() {\r\n");
      out.write("\t\t\tvar sel = dojo.byId(\"viewSelectSetMenu\");\r\n");
      out.write("\t\t\tvar viewSelect = sel.options[sel.selectedIndex].value;\r\n");
      out.write("\t\t\tvar vali = mod.generateInputMenu(viewSelect,true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction saveSettingPortal() {\r\n");
      out.write("\t\t\t//alert(dojo.toJson(settingPortalTempStore));\r\n");
      out.write("\t\t\t//unieap.debug(settingPortalTempHeight);\r\n");
      out.write("\t\t\t//document.writeln(dojo.toJson(settingPortalTempStore));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//dojo.cookie(\"viewToMenuRela\" + employeeid,dojo.toJson(settingPortalTempStore));  暂时删除视图设置功能\r\n");
      out.write("\t\t\tdojo.cookie(\"menuHeightSetting\" + employeeid,dojo.toJson(settingPortalTempHeight));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar viewValue = dojo.byId(\"viewSel\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar viewId = viewValue.options[viewValue.selectedIndex].value;\r\n");
      out.write("            mod.clearPortalContainer();\r\n");
      out.write("            mod.unsubscribeAllHandler();\r\n");
      out.write("           \r\n");
      out.write("\t\t\tmod.createPortalet(viewId);\r\n");
      out.write("\t\t\tmod.createPortaletSubMenu();\r\n");
      out.write("\t\t\t//dojo.byId(\"id1_tooltip\").close();\r\n");
      out.write("\t\t\tdijit.byId('id1_tooltip').onCancel();\r\n");
      out.write("\t\t\t//unieap.debug(settingPortalTempHeight);\r\n");
      out.write("\t\t\t//settingPortalTempStore.setData(dojo.fromJson(dojo.cookie(\"viewToMenuRela\" + employeeid)));\r\n");
      out.write("\t\t\t//settingPortalTempStore = dojo.fromJson(dojo.cookie(\"viewToMenuRela\" + employeeid));\r\n");
      out.write("\t\t\t//alert(\"1111\");\r\n");
      out.write("\t\t\t//unieap.debug(dojo.cookie(\"menuHeightSetting\" + employeeid));\r\n");
      out.write("\t\t\t//var cookieviewToMenuRela = dojo.fromJson(dojo.cookie(\"menuHeightSetting\" + employeeid));\r\n");
      out.write("\t\t\t//unieap.debug(cookieviewToMenuRela);\r\n");
      out.write("\t\t\t//settingPortalTempHeight = new dojo.store.Memory({\r\n");
      out.write("\t\t\t//\tdata: cookieviewToMenuRela[\"data\"]\r\n");
      out.write("\t\t\t//\t});\r\n");
      out.write("\t\t\t//unieap.debug(settingPortalTempHeight);\r\n");
      out.write("\t\t\t//unieap.debug(settingPortalTempStore.get(\"v01tempselect\"));\r\n");
      out.write("\t\t\t//var aa = mod.getMulSelectOptions(\"v02\");\r\n");
      out.write("\t\t\t//unieap.debug(aa);\r\n");
      out.write("\t\t\t//settingPortalTempStore.put(aa);\r\n");
      out.write("\t\t\t//alert(\"      \"+employeeid+\"  \" +   dojo.cookie(\"viewToMenuRela\" + employeeid));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("        //////////////////////////////////////////////////////////////\r\n");
      out.write("\t\tfunction publishInfos(topicName, infos) {\r\n");
      out.write("\t\t\t\tdojo.publish(topicName,infos);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction subscrubeInfos(topicName, menuId, method) {\r\n");
      out.write("\t\t\t var handler = dojo.subscribe(topicName,method);\r\n");
      out.write("\t\t\t handler.id = menuId+\"subHandler\";\r\n");
      out.write("\t\t\t mod.subscribeHandles.push(handler);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getTimeZone() {\r\n");
      out.write("\t\t\tvar now = new Date();\r\n");
      out.write("\t\t\tvar hour = now.getHours();\r\n");
      out.write("\t\t\tvar timez = \"\";\r\n");
      out.write("\t\t\tif(hour < 6){timez = \"凌晨好,<font color='blue's><b>");
      out.print(userNameDes);
      out.write("</b></font>\";}\r\n");
      out.write("\t\t\telse if (hour < 9){timez = \"早上好,<font color='blue'><b>");
      out.print(userNameDes);
      out.write("</b></font>\";}\r\n");
      out.write("\t\t\telse if (hour < 12){timez = \"上午好,<font color='blue'><b>");
      out.print(userNameDes);
      out.write("</b></font>\";}\r\n");
      out.write("\t\t\telse if (hour < 14){timez = \"中午好,<font color='blue'><b>");
      out.print(userNameDes);
      out.write("</b></font>\";}\r\n");
      out.write("\t\t\telse if (hour < 17){timez = \"下午好,<font color='blue'><b>");
      out.print(userNameDes);
      out.write("</b></font>\";}\r\n");
      out.write("\t\t\telse if (hour < 19){timez = \"傍晚好,<font color='blue'><b>");
      out.print(userNameDes);
      out.write("</b></font>\";}\r\n");
      out.write("\t\t\telse if (hour < 22){timez = \"晚上好,<font color='blue'><b>");
      out.print(userNameDes);
      out.write("</b></font>\";}\r\n");
      out.write("\t\t\telse {timez = \"夜里好,");
      out.print(userNameDes);
      out.write("\";}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdojo.byId(\"timezone\").innerHTML = timez;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"unieap\" style=\"overflow-y:auto;overflow-x:hidden;\">\r\n");
      out.write("<!--  -->\r\n");
      out.write("\r\n");
      out.write("<div height=\"5%\" style=\"overflow-y:hidden;overflow-x:hidden;\">\r\n");
      out.write("   <table width=\"100%\"><tr><td width=\"60%\">\r\n");
      out.write("        &nbsp;<img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_person.png\" width=\"16\" height=\"16\"/><span id=\"timezone\"></span>，欢迎登录河北电信CRM2.0系统!  &nbsp;&nbsp;当前系统在线人数：<span id=\"onlineNumner\"></span>\r\n");
      out.write("   <hr>\r\n");
      out.write("   </td>\r\n");
      out.write("   <td align=right>\r\n");
      out.write("       <table width=\"100%\" border=\"0\">\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td  align=\"right\">\r\n");
      out.write("                <span style=\"text-decoration:none;\">\r\n");
      out.write("                <div data-dojo-type=\"dijit.form.Button\" style=\"border:0\">\r\n");
      out.write("                   <span border=0 onclick=\"javascript:refleshPortalPage();\"><img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_refresh.png\" width=\"16\" height=\"16\" border=\"0\" style=\"bottom_margn:0\"/>刷新</span>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("               <span>\r\n");
      out.write("                 \r\n");
      out.write("                  <div id=\"tooltipDlgButton\" data-dojo-type=\"dijit.form.DropDownButton\" style=\"border:0\">\r\n");
      out.write("\t\t              <span border=0><img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_setting.png\" id=\"settingPortal11\" width=\"16\" height=\"16\" border=\"0\"/>设置</span>\r\n");
      out.write("\t\t              \r\n");
      out.write("\t\t              <div id=\"id1_tooltip\" data-dojo-type=\"dijit.TooltipDialog\" data-dojo-props='style:\"width: 480px; height: 450px;\",onShow:onSettingDiaShow' align=\"center\">\r\n");
      out.write("\t\t                <div style=\"align:center;width: 462px; height: 405px; display:none;border:1px solid #86b5e4\" id=\"alertDiv\" align=\"center\">\r\n");
      out.write("                             <table style=\"width:80%;height=80%;border:1px solid #86b5e4\" align=\"center\">\r\n");
      out.write("                             <tr>\r\n");
      out.write("                                 <td id='msgAlert' align=\"center\"></td>\r\n");
      out.write("                             </tr>\r\n");
      out.write("                             </table>\r\n");
      out.write("                         </div>\r\n");
      out.write("\r\n");
      out.write("                         <div class=\"claro\" id=\"settingDiv\">\r\n");
      out.write("\t\t\t              <div data-dojo-type=\"dijit.layout.TabContainer\" data-dojo-props='style:\"width: 462px; height: 405px;\"'>\r\n");
      out.write("\t\t\t\t\t\t\t<!--  \r\n");
      out.write("\t\t\t\t\t\t\t<div data-dojo-type=\"dijit.layout.ContentPane\" data-dojo-props='title:\"视图设置\"'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table style=\"width:100%;border:0px solid #86b5e4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td colspan=2>选择视图:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<select id=\"viewSelectSet\" onchange=\"checkviewSelectSet(this);\"></select><hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td colspan=2>\r\n");
      out.write("\t\t\t\t\t\t\t\t            <table style=\"width:100%;border:0px solid #86b5e4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t            <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t              <td align=right>可见主题&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t                <select id=\"selectViewsAll\" multiple data-dojo-type=\"dijit.form.MultiSelect\" size=\"12\" \r\n");
      out.write("\t\t\t\t\t\t\t\t                        data-dojo-props='style:{height:\"200px\", width:\"175px\", border:\"1px solid #86b5e4\"}'> </select>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t              </td>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t              <td align=center><br>\r\n");
      out.write("\t\t\t\t\t\t                          <button class=\"switch\" id=\"right\" onclick=\"leftToRight(0);\">＞</button><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t                  <button class=\"switch\" id=\"left\" onclick=\"leftToRight(1);\">＜</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t              </td>\t\t\t\t\t\t\t          \r\n");
      out.write("\t\t\t\t\t\t\t\t              <td align=left>&nbsp;&nbsp;&nbsp;&nbsp;当前视图主题<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t                <select id=\"selectViewsPoint\" multiple data-dojo-type=\"dijit.form.MultiSelect\" size=\"12\" \r\n");
      out.write("                                                        data-dojo-props='style:{height:\"200px\", width:\"175px\", border:\"1px solid #86b5e4\"}'> </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t              </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t              </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t              </table>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td align=right> <br><br><input type=button value=\"    应 用    \" onclick=\"applySettingClick();\" >&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t        <input type=button value=\"    取消    \" onclick=\"cancelSettingClick();\" ></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t<div data-dojo-type=\"dijit.layout.ContentPane\" data-dojo-props='title:\"窗口设置\"'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table style=\"width:100%;border:0px solid #86b5e4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td colspan=2>选择视图:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<select id=\"viewSelectSetMenu\" onchange=\"checkviewSelectSetHeight(this);\"></select><hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td colspan=2 id=\"settingPortaletHeightTd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td align=right> <br><br><input type=button value=\"    应 用    \" onclick=\"applySettingHeightClick();\" >&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t        <input type=button value=\"    取消    \" onclick=\"cancelSettingHeightClick();\" ></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t        <td>\r\n");
      out.write("\t\t\t\t\t\t\t\t        </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div align=center><input type=button value=\" 保存设置 \" onclick=\"saveSettingPortal();\"></input></div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                     \r\n");
      out.write("                     </div>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("               </span>\r\n");
      out.write("               <span>\r\n");
      out.write("               \r\n");
      out.write("                <div id=\"tooltipDlgButtonWenxin\" data-dojo-type=\"dijit.form.DropDownButton\" style=\"border:0\">\r\n");
      out.write("                  <span border=0><img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_wenxin.png\" width=\"16\" height=\"16\"/>温馨提示</span>\r\n");
      out.write("                  <div id=\"slowLoad\" data-dojo-type=\"dijit.TooltipDialog\" data-dojo-props='href:\"wenxin.jsp\"'></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                \r\n");
      out.write("             </span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("             \r\n");
      out.write("         </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("   </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("   <td>\r\n");
      out.write("       &nbsp;<img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_warning.png\" width=\"16\" height=\"16\"/>上次登录时间：<span id=\"lastLoginTime\"></span>&nbsp;&nbsp;&nbsp;&nbsp;<span style='display:none'>您有<span id=\"noReadWraning\"></span>条<font color='blue's><b>未读公告</b></font>，<span id=\"noComMission\"></span>条<font color='blue's><b>待办任务</b></font>，请尽快处理。</span>\r\n");
      out.write("   </td>\r\n");
      out.write("   <td align=right>视图选择：<select id=\"viewSel\" onchange=\"checkViewSel(this);\"></select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("   <span id=\"columnRate\" style=\"vertical-align: bottom; margin:0px;\"><img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_37.png\" onclick=\"checklayout('30,70');\"  alt=\"30:70\"/>\r\n");
      out.write("                         <img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_55.png\" onclick=\"checklayout('50,50');\"  alt=\"50:50\">\r\n");
      out.write("                         <img src=\"");
      out.print(webpath);
      out.write("/common/dx20/images/portal_73.png\" onclick=\"checklayout('70,30');\"  alt=\"70:30\">\r\n");
      out.write("                         </span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("   <!-- &nbsp;&nbsp;列宽设置(百分比)：<select id=\"layoutSel\" onchange=\"checklayout(this);\"></select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("          列数选择：<select id=\"colNumSel\" onchange=\"checkColNumSel(this);\"><option></option><option value=2>2</option><option value=3>3</option><option value=4>4</option></select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->\r\n");
      out.write("  </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    <div id=\"div-wellcome\" style=\"display: none\" align=center><br><br><br><br><br><br><br>欢迎进入CRM管理系统。</div>\r\n");
      out.write("\t<div dojoType=\"dojox.layout.GridContainer\"\r\n");
      out.write("\t\t\tid=\"gridContainer\"\r\n");
      out.write("\t\t\tisAutoOrganized=\"false\"\r\n");
      out.write("\t\t\tallowAutoScroll=\"false\" \r\n");
      out.write("\t\t\thasResizableColumns=\"false\"\r\n");
      out.write("\t\t\tdragHandleClass=\"dijitTitlePaneTitle\"\r\n");
      out.write("\t\t\tnbZones=\"2\"\r\n");
      out.write("\t\t\tstyle=\"width:100%;leftmargin=0;rightmargin=0;overflow-y:hidden;overflow-x:hidden;border:0px\"\r\n");
      out.write("\t\t\tdoLayout=\"false\" onkeydown=\"javascript:return;\">\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
