package com.neusoft.uniflow.web.webdesign.util.parser;


//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 16 09:43:36 CST 2003
//----------------------------------------------------


/** CUP generated class containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int OP_IN = 21;
  public static final int OP_LT = 15;
  public static final int PLUS = 9;
  public static final int FALSE = 8;
  public static final int OP_LE = 17;
  public static final int OP_EQ = 19;
  public static final int TRUE = 7;
  public static final int MINUS = 10;
  public static final int TIMES = 11;
  public static final int NUMBER = 6;
  public static final int STRING = 5;
  public static final int LPAREN = 13;
  public static final int EOF = 0;
  public static final int OP_NE = 20;
  public static final int OP_GT = 16;
  public static final int error = 1;
  public static final int NOT = 4;
  public static final int OP_GE = 18;
  public static final int RPAREN = 14;
  public static final int OP_INCLUDE = 22;
  public static final int AND = 3;
  public static final int DIVIDE = 12;
  public static final int OR = 2;
}

