dojo.provide("unieap.tests.module");
try{
	//注册logic测试地址
	dojo.registerModulePath("logic","../unieap/tests/robot/logic");
	//引入自动测试用例
	dojo.require("unieap.tests.robot.logic.ds.module");
	dojo.require("unieap.tests.robot.logic.form.module");
	dojo.require("unieap.tests.robot.logic.tree.module");
	dojo.require("unieap.tests.robot.logic.grid.module");
	dojo.require("unieap.tests.robot.logic.util.module");
}catch(e){
	doh.debug(e);
}
