var rowsetData = [{
    "id": "1231035443386",
    "label": "数据结构",
    "type": "menu",
    "parentID": "1212403325756",
    "leaf": false,
    "image": "null",
    "pagearea": "null",
    "location": "null",
    "chief": "false"
}, {
    "id": "1231037022343",
    "label": "业务模式",
    "type": "menu",
    "parentID": "1212403325756",
    "leaf": false,
    "image": "null",
    "pagearea": "null",
    "location": "null",
    "chief": "false"
}, {
    "id": "1213151337167",
    "label": "进度条",
    "type": "menu",
    "index": "1",
    "parentID": "1213062998781",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/form_progress.do",
    "chief": "true"
}, {
    "id": "1213322990999",
    "label": "普通树",
    "type": "menu",
    "index": "1",
    "parentID": "1213147310718",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/tree_common.do",
    "chief": "false"
}, {
    "id": "1213779176089",
    "label": "Tab",
    "type": "menu",
    "index": "1",
    "parentID": "1213778711197",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/layout_layout_tab.do",
    "chief": "false"
}, {
    "id": "1213783105111",
    "label": "Tab",
    "type": "menu",
    "index": "1",
    "parentID": "1213783070546",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/layout_auto_tab.do",
    "chief": "false"
}, {
    "id": "1213840053339",
    "label": "Tab与Tab",
    "type": "menu",
    "index": "1",
    "parentID": "1213840037794",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/layout_topbottom_tabandtab.do",
    "chief": "false"
}, {
    "id": "1213773892392",
    "label": "Tab与Tab",
    "type": "menu",
    "index": "1",
    "parentID": "1213773700289",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/layout_leftright_tabandtab.do",
    "chief": "false"
}, {
    "id": "1213779293907",
    "label": "一行Tab两列Form和Grid",
    "type": "menu",
    "index": "1",
    "parentID": "1213779276075",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/layout_topbottom2_tabandgridform.do",
    "chief": "false"
}, {
    "id": "1213864867687",
    "label": "一个Tree和两个Tab",
    "type": "menu",
    "index": "1",
    "parentID": "1213855712140",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/layout_leftright2_treeandtabtab.do",
    "chief": "false"
}, {
    "id": "1213154541588",
    "label": "普通对话框",
    "type": "menu",
    "index": "1",
    "parentID": "1213154530445",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/ria_simpledialog.do",
    "chief": "false"
}, {
    "id": "1214872081269",
    "label": "TitlePane",
    "type": "menu",
    "index": "1",
    "parentID": "1214871914688",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/container_titlepane.do",
    "chief": "false"
}, {
    "id": "1213063167970",
    "label": "演示样例",
    "type": "menu",
    "index": "1",
    "parentID": "1213063141603",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/ria_exceptiondemo.do",
    "chief": "false"
}, {
    "id": "1215420839554",
    "label": "HTTP",
    "type": "menu",
    "index": "1",
    "parentID": "1215420810003",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/ria_upload.do",
    "chief": "false"
}, {
    "id": "1216001130460",
    "label": "简单查询",
    "type": "menu",
    "index": "1",
    "parentID": "1216001113287",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/statement_simple.do",
    "chief": "false"
}, {
    "id": "1216888096775",
    "label": "基本用法",
    "type": "menu",
    "index": "1",
    "parentID": "1216888062550",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/pageauth_basic.do",
    "chief": "false"
}, {
    "id": "1217301450053",
    "label": "定义查询",
    "type": "menu",
    "index": "1",
    "parentID": "1217301388174",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/query_define.do",
    "chief": "false"
}, {
    "id": "export",
    "label": "导出",
    "type": "menu",
    "index": "1",
    "parentID": "1230020538593",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/grid_export.do",
    "chief": "false"
}, {
    "id": "rowlock",
    "label": "锁自定义行（小计合计）",
    "type": "menu",
    "index": "1",
    "parentID": "1228286392779",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/grid_rowlock.do",
    "chief": "false"
}, {
    "id": "editmode",
    "label": "编辑方式",
    "type": "menu",
    "index": "1",
    "parentID": "EditGrid",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/grid_editmode.do",
    "chief": "false"
}, {
    "id": "query",
    "label": "查询表格",
    "type": "menu",
    "index": "1",
    "parentID": "1229578655109",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/grid_query.do",
    "chief": "false"
}, {
    "id": "gridandform",
    "label": "表格和表单联动",
    "type": "menu",
    "index": "1",
    "parentID": "1229578772421",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/grid_gridandform.do",
    "chief": "false"
}, {
    "id": "pojoCRUD",
    "label": "主从表CRUD",
    "type": "menu",
    "index": "1",
    "parentID": "pojoDemo",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/multitable.do",
    "chief": "false"
}, {
    "id": "1228444859566",
    "label": "工具方法样例",
    "type": "menu",
    "index": "1",
    "parentID": "1228444836613",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/tool_api.do",
    "chief": "false"
}, {
    "id": "1228897005421",
    "label": "RIA版",
    "type": "menu",
    "index": "1",
    "parentID": "1228896990281",
    "leaf": true,
    "image": "null",
    "pagearea": "null",
    "location": "/jcaptcha_ria.do",
    "chief": "false"
}];

var treeStore = new unieap.ds.DataStore("menuTree", rowsetData);
var jsondata = "[{data:{id:'01',text:'01'},children:[{data:{text:'01-01',leaf:true}},{data:{text:'01-02'},children:[{data:{text:'01-02-01',leaf:true}},{data:{text:'01-02-02',leaf:true}}]},{data:{text:'01-03',leaf:true}}]},{data:{text:'02',leaf:true}}]"
	var dataCenter = new unieap.ds.DataCenter();
		dataCenter.addDataStore(treeStore);


var rowsetDataForLazyLoad = [
         					 {id:'1001',label:"节点",parentID:"",index:"8"},
         					 {id:'10011',label:"10011",parentID:"1001",index:"0"},
         					 {id:'1002',label:"1002",parentID:"",index:"1"},
         					 {id:'10012',label:"10012",parentID:"1002",index:"1"},
         					 {id:'10013',label:"10013",parentID:"1002",index:"3"},
         					 {id:'10014',label:"10014",parentID:"1002",index:"2"},
         					 {id:'100141',label:"100141",parentID:"10014",index:"1"},
         					 {id:'100142',label:"100142",parentID:"10014",index:"0"},
         					 {id:'10015',label:"10015",parentID:"1002",index:"0"},
         					 {id:'1006',label:"节点6",parentID:"",index:"2"},
         					 {id:'1007',label:"节点7",parentID:"",index:"3"}
        				   ];
var treeStoreForLazyLoad = new unieap.ds.DataStore("lazyload",rowsetDataForLazyLoad);
