function generate_contract_table(hear_info,table_info)
{
	var html_info = "";
	table_len = table_info.length;
	if(table_len>0)
	{
	for(i=0; i<table_len; i++)
	{
		html = "<tr>";
		html+= "<table border='2' cellpadding='1' cellspacing='2' width='620' bordercolor='#E6E6E6' bgcolor='#FFFFFF'>";	
		html+="<tr class='newtrType'>";		
		html+="<td width='100%' bgcolor='#E6E6E6' align='center' colspan = '4'>"+hear_info+"</td>";
		html+="</tr>";
		html+="</table>";
		html+="<table border='2' cellpadding='1' cellspacing='2' width='620' bordercolor='#E6E6E6' bgcolor='#FFFFFF'>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同编号</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][0]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同名称</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][1]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>客户编号</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][2]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>客户名称</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][3]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>客户经理</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][4]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>客户经理部门</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][5]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同类型</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][6]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同状态</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][7]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>合同金额</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][8]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>上级合同编号</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][9]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>综合布线投资</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][10]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>线路设备投资</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][11]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>大客户平均ARPU值</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][12]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>预期总成本回收期限</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][13]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>涉及产品</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][14]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同负责人</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][15]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>甲方签署人</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][16]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>乙方签署人</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][17]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同拟订人</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][18]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同审核人</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][19]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>合同归档人</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][20]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同作废操作人</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][21]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>签订日期</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][22]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>生效日期</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][23]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>失效日期</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][24]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>审核日期</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][25]+"</td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'>归档日期</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][26]+"</td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>作废日期</td>";
		html+="<td width='17%' bgcolor='#E6E6E6'>"+table_info[i][27]+"</td>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'></td>";
		html+="<td width='17%' bgcolor='#E6E6E6'></td>";
		html+="<td width='17%' align='center' bgcolor='#A2BEE1'></td>";
		html+="<td width='17%' bgcolor='#E6E6E6'></td>";
		html+="</tr>";
		html+="<tr class='newtrType'>";
		html+="<table border='1' cellpadding='1' cellspacing='2' width='620' bordercolor='#E6E6E6' bgcolor='#FFFFFF'>";
		html+="<tr class='newtrType'>";
		html+="<td width='16%' align='center' bgcolor='#A2BEE1'>合同备注</td>";
		html+="<td width='84%' bgcolor='#E6E6E6'>"+table_info[i][28]+"</td>";
		html+="</tr>";
		html+="</table>";
		html+="</tr>";
		html+="<table border='2' cellpadding='1' cellspacing='2' width='620' bordercolor='#E6E6E6' bgcolor='#FFFFFF'>";
		html+="<tr class='newtrType'>";       
		html+="<td align = 'center' width='10' bgcolor='#A2BEE1'>合同协议描述</td>";
		html+="<td width='610' bgcolor='#E6E6E6'>";
		html+="<textarea name='Contract_info' rows='8' cols='81' wrap='physical' value=''/ disabled='true'>"+table_info[i][29];
		html+="</textarea>"; 
		html+="</td>"; 
		html+="</tr>";
		html+="</table>";
		html+= "</tr>";
		html_info = html_info+html;
	}
}
	return html_info;

}
