dojo.provide("unieap.tests.robot.logic.grid.module");
try{
	doh.registerUrl('表格-绑定测试',
		dojo.moduleUrl('logic','grid/basic/test_grid_binding.html'),999999);
	doh.registerUrl('表格-选择测试-多选',
		dojo.moduleUrl('logic','grid/selection/test_grid_select_multiple.html'),999999);
	doh.registerUrl('表格-选择测试-单选',
		dojo.moduleUrl('logic','grid/selection/test_grid_select_single.html'),999999);
	doh.registerUrl('表格-选择测试-设置选择方式',
		dojo.moduleUrl('logic','grid/selection/test_grid_select_setSelectType.html'),999999);
}catch(e){
	alert('发现错误！！'+e.toString());
}